global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  # API Gateway
  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8888']
        labels:
          application: 'API Gateway'

  # Participant Service
  - job_name: 'participant-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          application: 'Participant Service'

  # Training Service
  - job_name: 'training-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'Training Service'

  # Discovery Service (Eureka)
  - job_name: 'discovery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8761']
        labels:
          application: 'Discovery Service'

  # Config Service
  - job_name: 'config-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9999']
        labels:
          application: 'Config Service'